# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: broadway-tix
# app and org for use with dashboard.serverless.com
app: broadway-tix
org: jegathings

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
custom:
  settings:
    TABLE: broadway_people

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
   - Effect: "Allow"
     Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
     Resource:
      - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.TABLE}"

functions:
  createPost:
    handler: handler.createReservation
    events:
    - http:
        path: /post
        method: post
  getAllPosts:
    handler: handler.getAllReservations
    events:
    - http:
        path: /posts
        method: get      